"""create workloads table

Revision ID: 028a72bb462f
Revises: 20387a998e78
Create Date: 2026-09-21 08:08:27.189618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028a72bb462f'
down_revision = '20387a998e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_calculated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workloads')
    # ### end Alembic commands ###
